### ISSUE TITLE
Deploy production and preproduction in the same server

### ISSUE THREAD

**Issue by alerodrom** [consul/installer#55]
Hi Consul commnunity!

I want to display production and preproduction on the same server. I can install the production environment on the server, but when I try to do the same with the preproduction environment I get an error.

![error-consul-preproduction](https://user-images.githubusercontent.com/14248341/48127377-db249100-e283-11e8-9fa1-5c67396a8292.png)

Capistrano's task is aborted, and he does not continue to deploy.

_deploy-secrets.yml_
```
preproduction:
  deploy_to: "/home/deploy/preproduction-consul"
  ssh_port: "22"
  server1: "my-server-ip"
  db_server: "localhost"
  user: "deploy"
  server_name: "my-web1.com"
  full_app_name: "preproduction-consul"

production:
  deploy_to: "/home/deploy/consul"
  ssh_port: "22"
  server1: "my-server-ip"
  db_server: "localhost"
  user: "deploy"
  server_name: "my-web.com"
  full_app_name: "consul"
```
Production and preproduction have to be on the same server. But the domains of the application are different.

If you need anything else, let me know.

Thanks!
